#!/bin/bash

# Check if the MariaDB setup is already done by checking the /run/mysqld directory
if [ ! -d /run/mysqld ]; then

    echo "Setting up MariaDB"

    # Create the mysqld run directory and set proper permissions
    mkdir -p /run/mysqld
    chown -R mysql:mysql /run/mysqld
    chown -R mysql:mysql /var/lib/mysql

    # Initialize the MariaDB database
    mysql_install_db --basedir=/usr --datadir=/var/lib/mysql --user=mysql

    # Create the SQL script for setting up the database and users
    cat << EOF > /tmp/init.sql
    USE mysql;
    FLUSH PRIVILEGES;

    DELETE FROM mysql.user WHERE User='';
    DROP DATABASE IF EXISTS test;
    DELETE FROM mysql.db WHERE Db='test';

    ALTER USER 'root'@'localhost' IDENTIFIED BY '${DB_ROOT}';

    CREATE DATABASE IF NOT EXISTS ${DB_NAME} CHARACTER SET utf8 COLLATE utf8_general_ci;

    CREATE USER IF NOT EXISTS '${DB_USER}'@'%';
    SET PASSWORD FOR '${DB_USER}'@'%' = PASSWORD('${DB_PASS}');
    GRANT ALL PRIVILEGES ON ${DB_NAME}.* TO '${DB_USER}'@'%';
    FLUSH PRIVILEGES;
EOF

    # Run the SQL script using the MariaDB bootstrap mode
    mysqld --user=mysql --bootstrap < /tmp/init.sql

    # Remove the temporary SQL file
    rm -f /tmp/init.sql
fi

# Start the MariaDB server in foreground mode
echo "MariaDB started"
exec mysqld --user=mysql --console

